# Generated by Django 2.2.7 on 2019-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191129_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': '测试'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default='', verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(default='', verbose_name='个性签名'),
        ),
    ]
