# Generated by Django 2.2.7 on 2019-12-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191129_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100, verbose_name='')),
                ('video_context', models.CharField(max_length=100, verbose_name='')),
                ('video_image', models.CharField(max_length=100, verbose_name='')),
                ('video_url', models.CharField(max_length=100, verbose_name='')),
                ('video_praise_number', models.IntegerField()),
                ('video_comments_number', models.IntegerField()),
                ('video_share_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '视频',
            },
        ),
    ]
