# Generated by Django 2.2.7 on 2019-12-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
    ]
