# Generated by Django 2.2.7 on 2019-12-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_video_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, verbose_name='内容')),
                ('hashId', models.CharField(max_length=200, verbose_name='内容')),
                ('unixTime', models.CharField(max_length=100, verbose_name='')),
                ('updateTime', models.CharField(max_length=100, verbose_name='更新时间')),
                ('url', models.CharField(max_length=1000, verbose_name='图片地址')),
            ],
            options={
                'verbose_name_plural': '聚合笑话',
            },
        ),
    ]
