# Generated by Django 2.2.7 on 2019-12-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_joke_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='hashId',
            field=models.CharField(max_length=200, verbose_name='hashId'),
        ),
    ]
